export type CatalogueProduct = {
  model: string;
  name: string;
  category: string;
  image: string;
  specs: { label: string; value: string }[];
  description: string;
  tier?: string; // "Essential" | "Premium" | "Lux" — product quality tier
  price?: string; // SSP price (e.g. "₹6,700")
};

export type CatalogueCategory = {
  slug: string;
  name: string;
  products: CatalogueProduct[];
};

export const CATALOGUE_CATEGORIES: CatalogueCategory[] = [
  {
    slug: "mini-bar",
    name: "Mini Bar",
    products: [
      // ── ESSENTIAL TIER ──────────────────────────────────
      {
        model: "LRMB-132",
        name: "45L Solid Door Compressor Mini Bar",
        category: "Mini Bar",
        image: "/images/product-catalogue/ssp-minibars/minibar-LRMB-132.jpg",
        description: "Automatic defrost, low noise and vibration, LED light inside, right side open, 1 pc shelf, temperature range: 0°C – 10°C.",
        tier: "Essential",
        price: "₹6,700",
        specs: [
          { label: "Capacity", value: "45 Litres" },
          { label: "Cooling", value: "Compressor" },
          { label: "Door", value: "Solid, Right Open" },
          { label: "Shelves", value: "1 Glass" },
          { label: "Temp Range", value: "0°C – 10°C" },
          { label: "Color", value: "Black" },
          { label: "SSP", value: "₹6,700" },
        ],
      },
      {
        model: "LRMB-126",
        name: "30L Solid Door Thermoelectric Mini Bar",
        category: "Mini Bar",
        image: "/images/product-catalogue/ssp-minibars/minibar-LRMB-126.jpg",
        description: "Low noise & vibration, CFC free, internal LED light, right side open, 1 pc shelf. Temperature range: 5°C – 15°C. Size: W400 × D440 × H480mm.",
        tier: "Essential",
        price: "₹8,400",
        specs: [
          { label: "Capacity", value: "30 Litres" },
          { label: "Cooling", value: "Thermoelectric" },
          { label: "Door", value: "Solid, Right Open" },
          { label: "Shelves", value: "1 Glass" },
          { label: "Temp Range", value: "5°C – 15°C" },
          { label: "Size", value: "W400 × D440 × H480mm" },
          { label: "Color", value: "Black" },
          { label: "SSP", value: "₹8,400" },
        ],
      },
      {
        model: "LRMB-127",
        name: "30L Glass Door Thermoelectric Mini Bar",
        category: "Mini Bar",
        image: "/images/product-catalogue/ssp-minibars/minibar-LRMB-127.jpg",
        description: "Low noise & vibration, CFC free, internal LED light, right side open, 1 pc shelf. Temperature range: 7°C – 15°C. Size: W400 × D440 × H480mm.",
        tier: "Essential",
        price: "₹8,700",
        specs: [
          { label: "Capacity", value: "30 Litres" },
          { label: "Cooling", value: "Thermoelectric" },
          { label: "Door", value: "Glass, Right Open" },
          { label: "Shelves", value: "1 Glass" },
          { label: "Temp Range", value: "7°C – 15°C" },
          { label: "Size", value: "W400 × D440 × H480mm" },
          { label: "Color", value: "Black" },
          { label: "SSP", value: "₹8,700" },
        ],
      },
      // ── PREMIUM TIER ────────────────────────────────────
      {
        model: "LRMB-128",
        name: "40L Solid Door Thermoelectric Mini Bar",
        category: "Mini Bar",
        image: "/images/product-catalogue/ssp-minibars/minibar-LRMB-128.jpg",
        description: "Low noise & vibration, CFC free, internal LED light, right side open, 1 pc shelf. Temperature range: 5°C – 15°C. Size: W400 × D428 × H530mm.",
        tier: "Premium",
        price: "₹8,800",
        specs: [
          { label: "Capacity", value: "40 Litres" },
          { label: "Cooling", value: "Thermoelectric" },
          { label: "Door", value: "Solid, Right Open" },
          { label: "Shelves", value: "1 Glass" },
          { label: "Temp Range", value: "5°C – 15°C" },
          { label: "Size", value: "W400 × D428 × H530mm" },
          { label: "Color", value: "Black" },
          { label: "SSP", value: "₹8,800" },
        ],
      },
      {
        model: "LRMB-129",
        name: "40L Glass Door Thermoelectric Mini Bar",
        category: "Mini Bar",
        image: "/images/product-catalogue/ssp-minibars/minibar-LRMB-129.jpg",
        description: "Low noise & vibration, CFC free, internal LED light, right side open, 1 pc shelf. Temperature range: 7°C – 15°C. Size: W400 × D428 × H530mm.",
        tier: "Premium",
        price: "₹9,200",
        specs: [
          { label: "Capacity", value: "40 Litres" },
          { label: "Cooling", value: "Thermoelectric" },
          { label: "Door", value: "Glass, Right Open" },
          { label: "Shelves", value: "1 Glass" },
          { label: "Temp Range", value: "7°C – 15°C" },
          { label: "Size", value: "W400 × D428 × H530mm" },
          { label: "Color", value: "Black" },
          { label: "SSP", value: "₹9,200" },
        ],
      },
      {
        model: "LRMB-130",
        name: "30L Solid Door (Mirror Finish) Absorption Mini Bar",
        category: "Mini Bar",
        image: "/images/product-catalogue/ssp-minibars/minibar-LRMB-130.jpg",
        description: "Zero noise and vibration, internal LED light, right side open, 1 pc shelf. Temperature range: 5°C – 12°C. Size: W400 × D420 × H460mm. Mirror finish door.",
        tier: "Premium",
        price: "₹9,200",
        specs: [
          { label: "Capacity", value: "30 Litres" },
          { label: "Cooling", value: "Absorption" },
          { label: "Door", value: "Solid Mirror Finish, Right Open" },
          { label: "Shelves", value: "1 Glass" },
          { label: "Temp Range", value: "5°C – 12°C" },
          { label: "Size", value: "W400 × D420 × H460mm" },
          { label: "Color", value: "Black" },
          { label: "SSP", value: "₹9,200" },
        ],
      },
      // ── LUX TIER ────────────────────────────────────────
      {
        model: "LRMB-131",
        name: "40L Solid Door (Mirror Finish) Absorption Mini Bar",
        category: "Mini Bar",
        image: "/images/product-catalogue/ssp-minibars/minibar-LRMB-131.jpg",
        description: "Zero noise and vibration, internal LED light, right side open, 1 pc shelf. Temperature range: 5°C – 12°C. Size: W400 × D425 × H550mm. Premium mirror finish door for luxury rooms.",
        tier: "Lux",
        price: "₹9,800",
        specs: [
          { label: "Capacity", value: "40 Litres" },
          { label: "Cooling", value: "Absorption" },
          { label: "Door", value: "Solid Mirror Finish, Right Open" },
          { label: "Shelves", value: "1 Glass" },
          { label: "Temp Range", value: "5°C – 12°C" },
          { label: "Size", value: "W400 × D425 × H550mm" },
          { label: "Color", value: "Black" },
          { label: "SSP", value: "₹9,800" },
        ],
      },
    ],
  },
  {
    slug: "kettle-set",
    name: "Tea Kettle & TCM Tray",
    products: [
      // ── TEA KETTLES ──────────────────────────────────────
      // ── PREMIUM TIER ────────────────────────────────────
      {
        model: "LRWT-155",
        name: "0.8L Electric Kettle — Double Layer SS304",
        category: "Kettle Set",
        image: "/images/product-catalogue/ssp-kettles/kettle-LRWT-155.jpg",
        description: "0.8L electric kettle, double layer with SS 304 food-grade inner stainless steel body. Matt finish PP outer surface. Automatic shut-off, anti-scalding. Power: 220V, 50Hz, 1200W.",
        tier: "Premium",
        price: "₹1,104",
        specs: [
          { label: "Capacity", value: "0.8 Litre" },
          { label: "Material", value: "SS304 Inner + PP Outer" },
          { label: "Power", value: "1200W, 220V 50Hz" },
          { label: "Features", value: "Auto Shut-off, Anti-Scalding" },
          { label: "Body", value: "Double Layer" },
          { label: "Color", value: "Black / White" },
          { label: "SSP", value: "₹1,104" },
        ],
      },
      {
        model: "LRWT-146",
        name: "0.6L Electric Kettle — Wooden Finish",
        category: "Kettle Set",
        image: "/images/product-catalogue/ssp-kettles/kettle-LRWT-146.jpg",
        description: "0.6L electric kettle with wooden finish and 304 SS inner body. Power: 220V-240V, 50-60Hz, 1000W. Stylish wooden exterior with food-grade steel interior.",
        tier: "Premium",
        price: "₹1,264",
        specs: [
          { label: "Capacity", value: "0.6 Litre" },
          { label: "Material", value: "304 SS Inner + Wooden Finish" },
          { label: "Power", value: "1000W, 220-240V 50-60Hz" },
          { label: "Features", value: "Auto Shut-off" },
          { label: "Color", value: "Wooden + SS" },
          { label: "SSP", value: "₹1,264" },
        ],
      },
      // ── LUX TIER ────────────────────────────────────────
      {
        model: "LRWT-150",
        name: "0.8L Electric Kettle — Strix Controller, Pastel",
        category: "Kettle Set",
        image: "/images/product-catalogue/ssp-kettles/kettle-LRWT-150.jpg",
        description: "0.8L electric kettle with premium Strix controller. Pastel off-white finish. Power: 220-240V, 50-60Hz, 1000W. Luxury tier for premium rooms.",
        tier: "Lux",
        price: "₹1,320",
        specs: [
          { label: "Capacity", value: "0.8 Litre" },
          { label: "Controller", value: "Strix (Premium)" },
          { label: "Power", value: "1000W, 220-240V 50-60Hz" },
          { label: "Features", value: "Auto Shut-off" },
          { label: "Color", value: "Off-white + Pastel" },
          { label: "SSP", value: "₹1,320" },
        ],
      },
      {
        model: "LRWT-156",
        name: "1L Electric Kettle — Strix Controller, Double Layer",
        category: "Kettle Set",
        image: "/images/product-catalogue/ssp-kettles/kettle-LRWT-156.jpg",
        description: "1L electric kettle with Strix controller. Double layer body with SS 304 food-grade inner stainless steel, PP housing outer. Anti-scratch round spout, flat lid design. Auto shut-off, anti-scalding. Power: 220V, 50Hz, 1000W.",
        tier: "Lux",
        price: "₹1,400",
        specs: [
          { label: "Capacity", value: "1.0 Litre" },
          { label: "Controller", value: "Strix (Premium)" },
          { label: "Material", value: "SS304 Inner + PP Outer" },
          { label: "Power", value: "1000W, 220V 50Hz" },
          { label: "Features", value: "Auto Shut-off, Anti-Scalding, Anti-Scratch" },
          { label: "Body", value: "Double Layer, Flat Lid" },
          { label: "Color", value: "Black" },
          { label: "SSP", value: "₹1,400" },
        ],
      },
      // ── TCM TRAYS (Tea/Coffee Maker Trays) ─────────────
      // ── ESSENTIAL TIER ──────────────────────────────────
      {
        model: "LRWT-160",
        name: "TCM Tray Set — ABS Material",
        category: "Kettle Set",
        image: "/images/product-catalogue/ssp-trays/tray-LRWT-160.jpg",
        description: "TCM tray set comprising main tray and sachet holder. Made in ABS material. Suitable for all kettles. Size: W380 × D260 × H55mm.",
        tier: "Essential",
        price: "₹400",
        specs: [
          { label: "Material", value: "ABS" },
          { label: "Includes", value: "Main Tray + Sachet Holder" },
          { label: "Size", value: "W380 × D260 × H55mm" },
          { label: "Compatibility", value: "All Kettle Types" },
          { label: "Color", value: "Black" },
          { label: "SSP", value: "₹400" },
        ],
      },
      {
        model: "LRWT-158",
        name: "TCM Tray with Anti-Theft Mechanism — ABS",
        category: "Kettle Set",
        image: "/images/product-catalogue/ssp-trays/tray-LRWT-158.jpg",
        description: "TCM tray with anti-theft mechanism. In-built sachet holder, separate compartment for stirrer, water spill collector. Made in ABS material. Size: W440 × D225 × H30mm.",
        tier: "Essential",
        price: "₹706",
        specs: [
          { label: "Material", value: "ABS" },
          { label: "Features", value: "Anti-Theft, Sachet Holder, Stirrer Compartment" },
          { label: "Size", value: "W440 × D225 × H30mm" },
          { label: "Compatibility", value: "All Kettle Types" },
          { label: "Color", value: "Black" },
          { label: "SSP", value: "₹706" },
        ],
      },
      {
        model: "LRWT-161",
        name: "TCM Tray with Anti-Theft — ABS, Compact",
        category: "Kettle Set",
        image: "/images/product-catalogue/ssp-trays/tray-LRWT-161.jpg",
        description: "TCM tray with anti-theft mechanism. In-built sachet holder, separate compartment for stirrer, water spill collector. Made in ABS material. Size: W355 × D235 × H30mm.",
        tier: "Essential",
        price: "₹650",
        specs: [
          { label: "Material", value: "ABS" },
          { label: "Features", value: "Anti-Theft, Sachet Holder, Stirrer Compartment" },
          { label: "Size", value: "W355 × D235 × H30mm" },
          { label: "Compatibility", value: "All Kettle Types" },
          { label: "Color", value: "Black / White" },
          { label: "SSP", value: "₹650" },
        ],
      },
      {
        model: "LRWT-168",
        name: "TCM Tray — Melamine with Sachet Holder",
        category: "Kettle Set",
        image: "/images/product-catalogue/ssp-trays/tray-LRWT-168.jpg",
        description: "TCM tray made in melamine material with sachet holder. Main tray size: W395 × D280 × H24mm. Sachet holder: 155 × 115 × 50mm.",
        tier: "Essential",
        price: "₹900",
        specs: [
          { label: "Material", value: "Melamine" },
          { label: "Includes", value: "Main Tray + Sachet Holder" },
          { label: "Main Tray Size", value: "W395 × D280 × H24mm" },
          { label: "Sachet Holder", value: "155 × 115 × 50mm" },
          { label: "Color", value: "Black" },
          { label: "SSP", value: "₹900" },
        ],
      },
      {
        model: "LRWT-171",
        name: "TCM Tray with Anti-Theft — Melamine",
        category: "Kettle Set",
        image: "/images/product-catalogue/ssp-trays/tray-LRWT-171.jpg",
        description: "TCM tray with anti-theft mechanism. In-built sachet holder, separate compartment for stirrer, water spill collector. Made in melamine material. Size: W440 × D225 × H30mm.",
        tier: "Essential",
        price: "₹975",
        specs: [
          { label: "Material", value: "Melamine" },
          { label: "Features", value: "Anti-Theft, Sachet Holder, Stirrer Compartment" },
          { label: "Size", value: "W440 × D225 × H30mm" },
          { label: "Compatibility", value: "All Kettle Types" },
          { label: "Color", value: "Black" },
          { label: "SSP", value: "₹975" },
        ],
      },
      // ── PREMIUM TIER TRAYS ──────────────────────────────
      {
        model: "LRWT-167",
        name: "TCM Tray with Anti-Theft — ABS + SS",
        category: "Kettle Set",
        image: "/images/product-catalogue/ssp-trays/tray-LRWT-167.jpg",
        description: "TCM tray with anti-theft mechanism. In-built sachet holder, separate compartment for stirrer, water spill collector. Made in ABS with SS accents. Size: W350 × D204 × H50mm.",
        tier: "Premium",
        price: "₹1,080",
        specs: [
          { label: "Material", value: "ABS + Stainless Steel" },
          { label: "Features", value: "Anti-Theft, Sachet Holder, Stirrer Compartment" },
          { label: "Size", value: "W350 × D204 × H50mm" },
          { label: "Compatibility", value: "All Kettle Types" },
          { label: "Color", value: "Black + SS" },
          { label: "SSP", value: "₹1,080" },
        ],
      },
      {
        model: "LRWT-166",
        name: "TCM Tray Complete Set — Melamine, Anti-Theft",
        category: "Kettle Set",
        image: "/images/product-catalogue/ssp-trays/tray-LRWT-166.jpg",
        description: "Complete TCM tray set with anti-theft mechanism. Includes main tray, sachet holder, and service tray for mugs and glasses. Made in melamine. Main tray: W380 × D300 × H22.5mm. Service tray: W335 × D130 × H11mm. Tea box: W155 × D115 × H50mm.",
        tier: "Premium",
        price: "₹1,080",
        specs: [
          { label: "Material", value: "Melamine" },
          { label: "Features", value: "Anti-Theft, Complete Set" },
          { label: "Includes", value: "Main Tray + Sachet Holder + Service Tray + Tea Box" },
          { label: "Main Tray", value: "W380 × D300 × H22.5mm" },
          { label: "Service Tray", value: "W335 × D130 × H11mm" },
          { label: "Tea Box", value: "W155 × D115 × H50mm" },
          { label: "Color", value: "Black" },
          { label: "SSP", value: "₹1,080" },
        ],
      },
      // ── LUX TIER TRAYS ──────────────────────────────────
      {
        model: "LRWT-170",
        name: "TCM Tray with Anti-Theft — Wooden Finish + SS",
        category: "Kettle Set",
        image: "/images/product-catalogue/ssp-trays/tray-LRWT-170.jpg",
        description: "TCM tray with anti-theft mechanism. ABS tray with wooden finish and SS accents. In-built sachet holder, separate compartment for stirrer, water spill collector. Size: W350 × D204 × H50mm.",
        tier: "Lux",
        price: "₹1,300",
        specs: [
          { label: "Material", value: "ABS + Wooden Finish + SS" },
          { label: "Features", value: "Anti-Theft, Sachet Holder, Stirrer Compartment" },
          { label: "Size", value: "W350 × D204 × H50mm" },
          { label: "Compatibility", value: "All Kettle Types" },
          { label: "Color", value: "Wooden + SS" },
          { label: "SSP", value: "₹1,300" },
        ],
      },
      {
        model: "LRWT-163",
        name: "TCM Tray — ABS with PU Leatherette Covering",
        category: "Kettle Set",
        image: "/images/product-catalogue/ssp-trays/tray-LRWT-163.jpg",
        description: "TCM tray comprising main tray and sachet holder. ABS body with PU leatherette covering. Suitable for all kettles. Size: W390 × D260 × H30mm.",
        tier: "Lux",
        price: "₹1,305",
        specs: [
          { label: "Material", value: "ABS + PU Leatherette" },
          { label: "Includes", value: "Main Tray + Sachet Holder" },
          { label: "Size", value: "W390 × D260 × H30mm" },
          { label: "Compatibility", value: "All Kettle Types" },
          { label: "Color", value: "Black + Grey" },
          { label: "SSP", value: "₹1,305" },
        ],
      },
      {
        model: "LRWT-159",
        name: "TCM Tray — Melamine, In-Built Compartments",
        category: "Kettle Set",
        image: "/images/product-catalogue/ssp-trays/tray-LRWT-159.jpg",
        description: "TCM tray with in-built compartments for sachet, stirrer, mugs, and water bottle. Made in melamine material. Suitable for all kettle types. Size: W420 × D300 × H28mm.",
        tier: "Lux",
        price: "₹1,305",
        specs: [
          { label: "Material", value: "Melamine" },
          { label: "Compartments", value: "Sachet, Stirrer, Mugs, Water Bottle" },
          { label: "Size", value: "W420 × D300 × H28mm" },
          { label: "Compatibility", value: "All Kettle Types" },
          { label: "Color", value: "Black" },
          { label: "SSP", value: "₹1,305" },
        ],
      },
      {
        model: "LRWT-164",
        name: "TCM Tray — Leatherette, Premium",
        category: "Kettle Set",
        image: "/images/product-catalogue/ssp-trays/tray-LRWT-164.jpg",
        description: "TCM tray made in leatherette. In-built sachet holder. Suitable for all kettle types. Size: W340 × D300 × H40mm. Luxury finish for premium rooms.",
        tier: "Lux",
        price: "₹1,350",
        specs: [
          { label: "Material", value: "Leatherette" },
          { label: "Features", value: "In-built Sachet Holder" },
          { label: "Size", value: "W340 × D300 × H40mm" },
          { label: "Compatibility", value: "All Kettle Types" },
          { label: "Color", value: "Black / Brown" },
          { label: "SSP", value: "₹1,350" },
        ],
      },
      {
        model: "LRWT-165",
        name: "TCM Tray with Anti-Theft — ABS + SS, Compact",
        category: "Kettle Set",
        image: "/images/product-catalogue/ssp-trays/tray-LRWT-165.jpg",
        description: "TCM tray with anti-theft mechanism. In-built sachet holder, separate compartment for stirrer, water spill collector. Made in ABS with SS accents. Size: W267 × D198 × H70mm.",
        tier: "Lux",
        price: "₹1,350",
        specs: [
          { label: "Material", value: "ABS + Stainless Steel" },
          { label: "Features", value: "Anti-Theft, Sachet Holder, Stirrer Compartment" },
          { label: "Size", value: "W267 × D198 × H70mm" },
          { label: "Compatibility", value: "All Kettle Types" },
          { label: "Color", value: "Black + SS" },
          { label: "SSP", value: "₹1,350" },
        ],
      },
      {
        model: "LRWT-162",
        name: "TCM Tray — Leatherette, Large",
        category: "Kettle Set",
        image: "/images/product-catalogue/ssp-trays/tray-LRWT-162.jpg",
        description: "TCM tray comprising main tray and sachet holder. Made in leatherette material. Suitable for all kettles. Size: W450 × D300 × H55mm. Large premium tray for luxury rooms.",
        tier: "Lux",
        price: "₹1,425",
        specs: [
          { label: "Material", value: "Leatherette" },
          { label: "Includes", value: "Main Tray + Sachet Holder" },
          { label: "Size", value: "W450 × D300 × H55mm" },
          { label: "Compatibility", value: "All Kettle Types" },
          { label: "Color", value: "Black" },
          { label: "SSP", value: "₹1,425" },
        ],
      },
    ],
  },
  {
    slug: "safe-box",
    name: "Safe Box",
    products: [
      {
        model: "SB-201",
        name: "Electronic Safe — Small",
        category: "Safe Box",
        image: "/images/product-catalogue/safe-box-SB-201.jpg",
        description: "Compact electronic safe with digital keypad. Ideal for standard hotel rooms.",
        specs: [
          { label: "Size", value: "200×300×200 mm" },
          { label: "Lock", value: "Digital keypad" },
          { label: "Material", value: "1.5mm steel" },
          { label: "Power", value: "4×AA + backup" },
          { label: "Override", value: "Emergency key" },
          { label: "Finish", value: "Black powder coat" },
        ],
      },
      {
        model: "SB-202",
        name: "Electronic Safe — Medium",
        category: "Safe Box",
        image: "/images/product-catalogue/safe-box-SB-202.jpg",
        description: "Medium electronic safe with laptop-friendly interior. Digital keypad + override.",
        specs: [
          { label: "Size", value: "250×350×250 mm" },
          { label: "Lock", value: "Digital keypad" },
          { label: "Material", value: "1.5mm steel" },
          { label: "Power", value: "4×AA + backup" },
          { label: "Override", value: "Emergency key" },
          { label: "Finish", value: "Black powder coat" },
        ],
      },
      {
        model: "SB-203",
        name: "Electronic Safe — Large",
        category: "Safe Box",
        image: "/images/product-catalogue/safe-box-SB-203.jpg",
        description: "Large electronic safe for suites. Fits laptops and larger valuables.",
        specs: [
          { label: "Size", value: "300×400×300 mm" },
          { label: "Lock", value: "Digital keypad" },
          { label: "Material", value: "2mm steel" },
          { label: "Power", value: "4×AA + backup" },
          { label: "Override", value: "Emergency key" },
          { label: "Finish", value: "Black powder coat" },
        ],
      },
      {
        model: "SB-204",
        name: "Electronic Safe — Deluxe",
        category: "Safe Box",
        image: "/images/product-catalogue/safe-box-SB-204.jpg",
        description: "Deluxe electronic safe with interior light and brass-trim finish.",
        specs: [
          { label: "Size", value: "300×400×300 mm" },
          { label: "Lock", value: "Digital keypad" },
          { label: "Material", value: "2mm steel" },
          { label: "Power", value: "4×AA + backup" },
          { label: "Override", value: "Emergency key" },
          { label: "Finish", value: "Brass-trim" },
        ],
      },
    ],
  },
  {
    slug: "door-lock",
    name: "Door Lock",
    products: [
      {
        model: "DL-301",
        name: "RFID Door Lock — Standard",
        category: "Door Lock",
        image: "/images/product-catalogue/door-lock-DL-301.jpg",
        description: "RFID card door lock with brass accent trim. Battery-powered, audit trail.",
        specs: [
          { label: "Access", value: "RFID card + key" },
          { label: "Battery", value: "4×AA (10,000 unlocks)" },
          { label: "Finish", value: "Brass / Black" },
          { label: "Audit trail", value: "Last 256 entries" },
          { label: "PMS integration", value: "Yes" },
          { label: "Warranty", value: "2 years" },
        ],
      },
      {
        model: "DL-302",
        name: "RFID Door Lock — Premium",
        category: "Door Lock",
        image: "/images/product-catalogue/door-lock-DL-302.jpg",
        description: "Premium RFID door lock with touch keypad and brass finish.",
        specs: [
          { label: "Access", value: "RFID + keypad + key" },
          { label: "Battery", value: "4×AA (10,000 unlocks)" },
          { label: "Finish", value: "Brass" },
          { label: "Audit trail", value: "Last 512 entries" },
          { label: "PMS integration", value: "Yes" },
          { label: "Warranty", value: "3 years" },
        ],
      },
      {
        model: "DL-303",
        name: "Docking Pod & Room Phone",
        category: "Door Lock",
        image: "/images/product-catalogue/door-lock-DL-303.jpg",
        description: "Docking pod with room telephone. Integrates with door lock system.",
        specs: [
          { label: "Function", value: "Phone + charging dock" },
          { label: "Integration", value: "Door lock PMS" },
          { label: "Finish", value: "Brass / Black" },
          { label: "Warranty", value: "2 years" },
          { label: "Power", value: "AC adapter" },
          { label: "Features", value: "Wake-up call, voicemail" },
        ],
      },
      {
        model: "DL-304",
        name: "Room Telephone",
        category: "Door Lock",
        image: "/images/product-catalogue/door-lock-DL-304.jpg",
        description: "Hotel room telephone with programmable keys and messaging.",
        specs: [
          { label: "Type", value: "Analog/VoIP" },
          { label: "Keys", value: "10 programmable" },
          { label: "Finish", value: "Brass / Black" },
          { label: "Warranty", value: "2 years" },
          { label: "Features", value: "Wake-up, voicemail, speaker" },
          { label: "Power", value: "Phone line / AC" },
        ],
      },
    ],
  },
  {
    slug: "hair-dryer",
    name: "Hair Dryer",
    products: [
      {
        model: "HD-501",
        name: "Wall-Mounted Hair Dryer 1600W",
        category: "Hair Dryer",
        image: "/images/product-catalogue/hair-dryer-HD-501.jpg",
        description: "Wall-mounted hotel hair dryer, 1600W with auto shut-off on release.",
        specs: [
          { label: "Power", value: "1600W" },
          { label: "Speed", value: "2-speed" },
          { label: "Mount", value: "Wall bracket" },
          { label: "Auto shut-off", value: "Yes" },
          { label: "Cable", value: "Retractable" },
          { label: "Finish", value: "Black + Brass" },
        ],
      },
      {
        model: "HD-502",
        name: "Wall-Mounted Hair Dryer 1800W",
        category: "Hair Dryer",
        image: "/images/product-catalogue/hair-dryer-HD-502.jpg",
        description: "Premium wall-mounted hair dryer, 1800W with dual speed and cool shot.",
        specs: [
          { label: "Power", value: "1800W" },
          { label: "Speed", value: "2-speed + cool" },
          { label: "Mount", value: "Wall bracket" },
          { label: "Auto shut-off", value: "Yes" },
          { label: "Cable", value: "Retractable" },
          { label: "Finish", value: "Black + Brass" },
        ],
      },
    ],
  },
  {
    slug: "magnifying-mirror",
    name: "Magnifying Mirror",
    products: [
      {
        model: "MM-601",
        name: "Magnifying Mirror 5× — Chrome",
        category: "Magnifying Mirror",
        image: "/images/product-catalogue/magnifying-mirror-MM-601.jpg",
        description: "Chrome-finished magnifying vanity mirror, 5× magnification, extendable arm.",
        specs: [
          { label: "Magnification", value: "5×" },
          { label: "Diameter", value: "180 mm" },
          { label: "Arm", value: "Extendable 300mm" },
          { label: "Finish", value: "Polished chrome" },
          { label: "Rotation", value: "360°" },
          { label: "Mount", value: "Wall-mounted" },
        ],
      },
      {
        model: "MM-602",
        name: "Magnifying Mirror 7× — Brass",
        category: "Magnifying Mirror",
        image: "/images/product-catalogue/magnifying-mirror-MM-602.jpg",
        description: "Brass-finished magnifying vanity mirror, 7× magnification, extendable arm.",
        specs: [
          { label: "Magnification", value: "7×" },
          { label: "Diameter", value: "200 mm" },
          { label: "Arm", value: "Extendable 350mm" },
          { label: "Finish", value: "Polished brass" },
          { label: "Rotation", value: "360°" },
          { label: "Mount", value: "Wall-mounted" },
        ],
      },
    ],
  },
  {
    slug: "hand-dryer",
    name: "Hand Dryer",
    products: [
      {
        model: "HD-701",
        name: "Commercial Hand Dryer 1400W",
        category: "Hand Dryer",
        image: "/images/product-catalogue/hand-dryer-HD-701.jpg",
        description: "High-speed commercial hand dryer, 1400W. Dries in 10 seconds, HEPA filter.",
        specs: [
          { label: "Dry time", value: "10 seconds" },
          { label: "Power", value: "1400W" },
          { label: "Filter", value: "HEPA H13" },
          { label: "Noise", value: "< 70 dB" },
          { label: "Material", value: "SS304" },
          { label: "Sensor", value: "Infrared" },
        ],
      },
      {
        model: "HD-702",
        name: "Commercial Hand Dryer 1600W",
        category: "Hand Dryer",
        image: "/images/product-catalogue/hand-dryer-HD-702.jpg",
        description: "Premium hand dryer, 1600W with brass accent trim. HEPA filter, low noise.",
        specs: [
          { label: "Dry time", value: "8 seconds" },
          { label: "Power", value: "1600W" },
          { label: "Filter", value: "HEPA H13" },
          { label: "Noise", value: "< 68 dB" },
          { label: "Material", value: "SS304 + Brass" },
          { label: "Sensor", value: "Infrared" },
        ],
      },
    ],
  },
  {
    slug: "luggage-trolley",
    name: "Luggage Trolley",
    products: [
      {
        model: "LT-801",
        name: "Luggage Trolley — Standard",
        category: "Luggage Trolley",
        image: "/images/product-catalogue/luggage-trolley-LT-801.jpg",
        description: "Standard hotel luggage trolley with brass frame and carpeted platform.",
        specs: [
          { label: "Load", value: "200 kg" },
          { label: "Frame", value: "Brass-plated steel" },
          { label: "Platform", value: "Carpeted" },
          { label: "Wheels", value: "4× silent castor" },
          { label: "Size", value: "1100×600×950 mm" },
          { label: "Finish", value: "Brass" },
        ],
      },
      {
        model: "LT-802",
        name: "Luggage Trolley — Deluxe",
        category: "Luggage Trolley",
        image: "/images/product-catalogue/luggage-trolley-LT-802.jpg",
        description: "Deluxe luggage trolley with ornate brass frame and leather straps.",
        specs: [
          { label: "Load", value: "250 kg" },
          { label: "Frame", value: "Brass-plated steel" },
          { label: "Platform", value: "Carpeted + straps" },
          { label: "Wheels", value: "4× silent castor" },
          { label: "Size", value: "1200×650×1000 mm" },
          { label: "Finish", value: "Brass" },
        ],
      },
      {
        model: "LT-803",
        name: "Housekeeping Trolley",
        category: "Luggage Trolley",
        image: "/images/product-catalogue/luggage-trolley-LT-803.jpg",
        description: "Housekeeping trolley with shelves and linen bag. For room service.",
        specs: [
          { label: "Load", value: "150 kg" },
          { label: "Frame", value: "Steel, powder-coated" },
          { label: "Features", value: "Shelves + linen bag" },
          { label: "Wheels", value: "4× silent castor" },
          { label: "Size", value: "1000×550×1200 mm" },
          { label: "Finish", value: "Brass / Black" },
        ],
      },
      {
        model: "LT-804",
        name: "Linen Trolley",
        category: "Luggage Trolley",
        image: "/images/product-catalogue/luggage-trolley-LT-804.jpg",
        description: "Linen trolley for housekeeping. Large capacity with separate compartments.",
        specs: [
          { label: "Load", value: "120 kg" },
          { label: "Frame", value: "Steel, powder-coated" },
          { label: "Compartments", value: "2" },
          { label: "Wheels", value: "4× silent castor" },
          { label: "Size", value: "900×500×1100 mm" },
          { label: "Finish", value: "Black" },
        ],
      },
    ],
  },
];
